//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
//There is a bug with the xsd.exe tool where the notes field of the patchType class is generated with type textType[][] instead of textType[] and this must be changed manually.
namespace CWEBot.Models {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://scap.nist.gov/schema/feed/vulnerability/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://scap.nist.gov/schema/feed/vulnerability/2.0", IsNullable=false)]
    public partial class nvd {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entry", Order=0)]
        public vulnerabilityType[] entry;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal nvd_xml_version;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime pub_date;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/vulnerability/0.4")]
    [System.Xml.Serialization.XmlRootAttribute("entry", Namespace="http://scap.nist.gov/schema/feed/vulnerability/2.0", IsNullable=false)]
    public partial class vulnerabilityType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("osvdb-ext", Order=0)]
        public osvdbExtensionType osvdbext;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vulnerable-configuration", Order=1)]
        public PlatformType[] vulnerableconfiguration;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("vulnerable-software-list", Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("product", DataType="anyURI", IsNullable=false)]
        public string[] vulnerablesoftwarelist;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cce-id", typeof(string), DataType="token", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("cve-id", typeof(string), DataType="token", Order=3)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("discovered-datetime", Order=5)]
        public System.DateTime discovereddatetime;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool discovereddatetimeSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("disclosure-datetime", Order=6)]
        public System.DateTime disclosuredatetime;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool disclosuredatetimeSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("exploit-publish-datetime", Order=7)]
        public System.DateTime exploitpublishdatetime;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool exploitpublishdatetimeSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("published-datetime", Order=8)]
        public System.DateTime publisheddatetime;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool publisheddatetimeSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("last-modified-datetime", Order=9)]
        public System.DateTime lastmodifieddatetime;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastmodifieddatetimeSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public cvssImpactType cvss;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("security-protection", Order=11)]
        public securityProtectionType securityprotection;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool securityprotectionSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("assessment_check", Order=12)]
        public checkReferenceType[] assessment_check;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cwe", Order=13)]
        public cweReferenceType[] cwe;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("references", Order=14)]
        public vulnerabilityReferenceType[] references;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fix_action", Order=15)]
        public fixActionType[] fix_action;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("scanner", Order=16)]
        public toolConfigurationType[] scanner;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string summary;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("technical_description", Order=18)]
        public referenceType[] technical_description;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attack_scenario", Order=19)]
        public referenceType[] attack_scenario;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string id;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/vulnerability/0.4")]
    public partial class osvdbExtensionType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("exploit-location", Order=0)]
        public associatedExploitLocationType exploitlocation;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/vulnerability/0.4")]
    public partial class associatedExploitLocationType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("physical-access", Order=0)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool physicalaccess;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("voluntarily-interact", Order=1)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool voluntarilyinteract;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool dialup;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool unknown;
        
        public associatedExploitLocationType() {
            this.physicalaccess = false;
            this.voluntarilyinteract = false;
            this.dialup = false;
            this.unknown = false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/vulnerability/0.4")]
    public partial class toolConfigurationType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=0)]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("definition", Order=1)]
        public checkReferenceType[] definition;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/scap-core/0.1")]
    public partial class checkReferenceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string system;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string href;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string name;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/patch/0.1")]
    [System.Xml.Serialization.XmlRootAttribute("patch", Namespace="http://scap.nist.gov/schema/patch/0.1", IsNullable=false)]
    public partial class patchType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public textType title;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("reference", IsNullable=false)]
        public referenceType[] references;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("note", typeof(textType), Namespace="http://scap.nist.gov/schema/scap-core/0.1", IsNullable=false)]
        public textType[] notes;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("check", Order=3)]
        public checkReferenceType[] check;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("supersedes", Order=4)]
        public patchType[] supersedes;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("superseded-by", Order=5)]
        public patchType[] supersededby;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double identifier;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool superseded;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool deprecated;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deprecatedSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(referenceType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/scap-core/0.1")]
    public partial class textType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string lang;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/scap-core/0.1")]
    public partial class referenceType : textType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string href;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/vulnerability/0.4")]
    public partial class fixActionType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://scap.nist.gov/schema/patch/0.1", Order=0)]
        public patchType patch;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("configuration-remediation", Order=1)]
        public vulnerabilityReferenceType configurationremediation;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("software-update", DataType="anyURI", Order=2)]
        public string[] softwareupdate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("notes", Order=3)]
        public string[] notes;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("deprecated-by", DataType="anyURI", Order=4)]
        public string[] deprecatedby;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("next-fix-action", Order=5)]
        public fixActionType[] nextfixaction;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fix-action-tool-configuration", Order=6)]
        public toolConfigurationType[] fixactiontoolconfiguration;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("applicable-configuration", Order=7)]
        public PlatformType[] applicableconfiguration;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public fixEffectivenessEnumType effectiveness;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool effectivenessSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("applicable-check", Order=9)]
        public checkReferenceType[] applicablecheck;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public fixActionDescriptionEnumType fix_action_description;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public fixActionTypeEnumType fix_action_type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string source;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/vulnerability/0.4")]
    public partial class vulnerabilityReferenceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string source;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public referenceType reference;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("note", Namespace="http://scap.nist.gov/schema/scap-core/0.1", IsNullable=false)]
        public textType[] notes;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string lang;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public vulnerabilityReferenceCategoryEnumType reference_type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool deprecated;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deprecatedSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/vulnerability/0.4")]
    public enum vulnerabilityReferenceCategoryEnumType {
        
        /// <remarks/>
        PATCH,
        
        /// <remarks/>
        VENDOR_ADVISORY,
        
        /// <remarks/>
        THIRD_PARTY_ADVISORY,
        
        /// <remarks/>
        SIGNATURE_SOURCE,
        
        /// <remarks/>
        MITIGATION_PROCEDURE,
        
        /// <remarks/>
        TOOL_CONFIGURATION_DESCRIPTION,
        
        /// <remarks/>
        UNKNOWN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cpe.mitre.org/language/2.0")]
    public partial class PlatformType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("title", Order=0)]
        public TextType[] title;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("remark", Order=1)]
        public TextType[] remark;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("logical-test", Order=2)]
        public LogicalTestType logicaltest;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string id;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cpe.mitre.org/language/2.0")]
    public partial class TextType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string lang;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cpe.mitre.org/language/2.0")]
    [System.Xml.Serialization.XmlRootAttribute("logical-test", Namespace="http://cpe.mitre.org/language/2.0", IsNullable=false)]
    public partial class LogicalTestType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("logical-test", Order=0)]
        public LogicalTestType[] logicaltest;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fact-ref", Order=1)]
        public FactRefType[] factref;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public operatorEnumeration @operator;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool negate;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cpe.mitre.org/language/2.0")]
    public partial class FactRefType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string name;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cpe.mitre.org/language/2.0")]
    public enum operatorEnumeration {
        
        /// <remarks/>
        AND,
        
        /// <remarks/>
        OR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/vulnerability/0.4")]
    public enum fixEffectivenessEnumType {
        
        /// <remarks/>
        PARTIAL,
        
        /// <remarks/>
        COMPLETE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/vulnerability/0.4")]
    public enum fixActionDescriptionEnumType {
        
        /// <remarks/>
        PATCH,
        
        /// <remarks/>
        SOFTWARE_UPDATE,
        
        /// <remarks/>
        CONFIGURATION_CHANGE,
        
        /// <remarks/>
        POLICY_CHANGE,
        
        /// <remarks/>
        EXTERNAL_MITIGATION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/vulnerability/0.4")]
    public enum fixActionTypeEnumType {
        
        /// <remarks/>
        MITIGATION,
        
        /// <remarks/>
        REMEDIATION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/vulnerability/0.4")]
    public partial class cweReferenceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string id;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/cvss-v2/0.2")]
    public partial class confidenceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool approximated;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public confidenceEnumType Value;
        
        public confidenceType() {
            this.approximated = false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/cvss-v2/0.2")]
    public enum confidenceEnumType {
        
        /// <remarks/>
        UNCONFIRMED,
        
        /// <remarks/>
        UNCORROBORATED,
        
        /// <remarks/>
        CONFIRMED,
        
        /// <remarks/>
        NOT_DEFINED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/cvss-v2/0.2")]
    public partial class remediationLevelType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool approximated;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public remediationLevelEnumType Value;
        
        public remediationLevelType() {
            this.approximated = false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/cvss-v2/0.2")]
    public enum remediationLevelEnumType {
        
        /// <remarks/>
        OFFICIAL_FIX,
        
        /// <remarks/>
        TEMPORARY_FIX,
        
        /// <remarks/>
        WORKAROUND,
        
        /// <remarks/>
        UNAVAILABLE,
        
        /// <remarks/>
        NOT_DEFINED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/cvss-v2/0.2")]
    public partial class exploitabilityType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool approximated;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public exploitabilityEnumType Value;
        
        public exploitabilityType() {
            this.approximated = false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/cvss-v2/0.2")]
    public enum exploitabilityEnumType {
        
        /// <remarks/>
        UNPROVEN,
        
        /// <remarks/>
        PROOF_OF_CONCEPT,
        
        /// <remarks/>
        FUNCTIONAL,
        
        /// <remarks/>
        HIGH,
        
        /// <remarks/>
        NOT_DEFINED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/cvss-v2/0.2")]
    public partial class ciaRequirementType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool approximated;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public ciaRequirementEnumType Value;
        
        public ciaRequirementType() {
            this.approximated = false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/cvss-v2/0.2")]
    public enum ciaRequirementEnumType {
        
        /// <remarks/>
        LOW,
        
        /// <remarks/>
        MEDIUM,
        
        /// <remarks/>
        HIGH,
        
        /// <remarks/>
        NOT_DEFINED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/cvss-v2/0.2")]
    public partial class targetDistributionType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool approximated;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public targetDistributionEnumType Value;
        
        public targetDistributionType() {
            this.approximated = false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/cvss-v2/0.2")]
    public enum targetDistributionEnumType {
        
        /// <remarks/>
        NONE,
        
        /// <remarks/>
        LOW,
        
        /// <remarks/>
        MEDIUM,
        
        /// <remarks/>
        HIGH,
        
        /// <remarks/>
        NOT_DEFINED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/cvss-v2/0.2")]
    public partial class collateralDamagePotentialType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool approximated;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public collateralDamagePotentialEnumType Value;
        
        public collateralDamagePotentialType() {
            this.approximated = false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/cvss-v2/0.2")]
    public enum collateralDamagePotentialEnumType {
        
        /// <remarks/>
        NONE,
        
        /// <remarks/>
        LOW,
        
        /// <remarks/>
        LOW_MEDIUM,
        
        /// <remarks/>
        MEDIUM_HIGH,
        
        /// <remarks/>
        HIGH,
        
        /// <remarks/>
        NOT_DEFINED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/cvss-v2/0.2")]
    public partial class ciaType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool approximated;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public ciaEnumType Value;
        
        public ciaType() {
            this.approximated = false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/cvss-v2/0.2")]
    public enum ciaEnumType {
        
        /// <remarks/>
        NONE,
        
        /// <remarks/>
        PARTIAL,
        
        /// <remarks/>
        COMPLETE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/cvss-v2/0.2")]
    public partial class authenticationType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool approximated;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public authenticationEnumType Value;
        
        public authenticationType() {
            this.approximated = false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/cvss-v2/0.2")]
    public enum authenticationEnumType {
        
        /// <remarks/>
        MULTIPLE_INSTANCES,
        
        /// <remarks/>
        SINGLE_INSTANCE,
        
        /// <remarks/>
        NONE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/cvss-v2/0.2")]
    public partial class accessComplexityType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool approximated;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public accessComplexityEnumType Value;
        
        public accessComplexityType() {
            this.approximated = false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/cvss-v2/0.2")]
    public enum accessComplexityEnumType {
        
        /// <remarks/>
        HIGH,
        
        /// <remarks/>
        MEDIUM,
        
        /// <remarks/>
        LOW,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/cvss-v2/0.2")]
    public partial class accessVectorType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool approximated;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public accessVectorEnumType Value;
        
        public accessVectorType() {
            this.approximated = false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/cvss-v2/0.2")]
    public enum accessVectorEnumType {
        
        /// <remarks/>
        LOCAL,
        
        /// <remarks/>
        ADJACENT_NETWORK,
        
        /// <remarks/>
        NETWORK,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(temporalMetricsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(environmentalMetricsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(baseMetricsType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/cvss-v2/0.2")]
    public abstract partial class metricsType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("upgraded-from-version")]
        public decimal upgradedfromversion;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool upgradedfromversionSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/cvss-v2/0.2")]
    public partial class temporalMetricsType : metricsType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal score;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool scoreSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("temporal-multiplier", Order=1)]
        public decimal temporalmultiplier;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool temporalmultiplierSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public exploitabilityType exploitability;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("remediation-level", Order=3)]
        public remediationLevelType remediationlevel;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("report-confidence", Order=4)]
        public confidenceType reportconfidence;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=5)]
        public string source;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("generated-on-datetime", Order=6)]
        public System.DateTime generatedondatetime;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/cvss-v2/0.2")]
    public partial class environmentalMetricsType : metricsType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal score;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool scoreSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("collateral-damage-potential", Order=1)]
        public collateralDamagePotentialType collateraldamagepotential;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("target-distribution", Order=2)]
        public targetDistributionType targetdistribution;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("confidentiality-requirement", Order=3)]
        public ciaRequirementType confidentialityrequirement;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("integrity-requirement", Order=4)]
        public ciaRequirementType integrityrequirement;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("availability-requirement", Order=5)]
        public ciaRequirementType availabilityrequirement;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=6)]
        public string source;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("generated-on-datetime", Order=7)]
        public System.DateTime generatedondatetime;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool generatedondatetimeSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/cvss-v2/0.2")]
    public partial class baseMetricsType : metricsType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal score;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool scoreSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("exploit-subscore", Order=1)]
        public decimal exploitsubscore;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool exploitsubscoreSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("impact-subscore", Order=2)]
        public decimal impactsubscore;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool impactsubscoreSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("access-vector", Order=3)]
        public accessVectorType accessvector;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("access-complexity", Order=4)]
        public accessComplexityType accesscomplexity;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public authenticationType authentication;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("confidentiality-impact", Order=6)]
        public ciaType confidentialityimpact;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("integrity-impact", Order=7)]
        public ciaType integrityimpact;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("availability-impact", Order=8)]
        public ciaType availabilityimpact;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=9)]
        public string source;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("generated-on-datetime", Order=10)]
        public System.DateTime generatedondatetime;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool generatedondatetimeSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cvssImpactType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/cvss-v2/0.2")]
    public partial class cvssType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("base_metrics", Order=0)]
        public baseMetricsType[] base_metrics;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("environmental_metrics", Order=1)]
        public environmentalMetricsType[] environmental_metrics;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("temporal_metrics", Order=2)]
        public temporalMetricsType[] temporal_metrics;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/cvss-v2/0.2")]
    public partial class cvssImpactType : cvssType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/vulnerability/0.4", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("cce-id")]
        cceid,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("cve-id")]
        cveid,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scap.nist.gov/schema/vulnerability/0.4")]
    public enum securityProtectionType {
        
        /// <remarks/>
        ALLOWS_ADMIN_ACCESS,
        
        /// <remarks/>
        ALLOWS_USER_ACCESS,
        
        /// <remarks/>
        ALLOWS_OTHER_ACCESS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cpe.mitre.org/language/2.0")]
    [System.Xml.Serialization.XmlRootAttribute("platform-specification", Namespace="http://cpe.mitre.org/language/2.0", IsNullable=false)]
    public partial class platformspecification {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("platform", Order=0)]
        public PlatformType[] platform;
    }
}
